
default: &default
  adapter: postgresql

development:
  <<: *default
  database: pickaplayer_development
test:
  <<: *default
  database: pickaplayer_test
production:
  <<: *default
  database: pickaplayer_production
